openapi: 3.0.3
info:
  title: OpenAPI schema for template .
components:
  schemas:
    variables:
      type: object
      properties:
        helm_release_name:
          title: Helm Release Name
          type: string
          description: The name of the Helm release.
          default: victoria-metrics-auth
          x-walrus-ui:
            group: Basic
            order: 1
        namespace_name:
          title: Namespace Name
          type: string
          description: The namespace where the Helm release will be installed.
          default: victoria-system
          x-walrus-ui:
            group: Basic
            order: 2
        helm_chart_version:
          title: Helm Chart Version
          type: string
          description: The version of the victoria-metrics-auth Helm chart.
          default: 0.4.13
          x-walrus-ui:
            group: Basic
            order: 3
        ingress_enabled:
          title: Ingress Enabled
          type: boolean
          description: Victoria Auth Ingress Enabled
          default: "true"
          x-walrus-ui:
            group: Basic
            order: 4
        domain_name:
          title: Domain Name
          type: string
          description: Domain name for Victoria Auth, e.g. 'dev.domainname.com'
          default: dev.domainname.com
          x-walrus-ui:
            group: Basic
            order: 5
        dash_domain_name:
          title: Dash Domain Name
          type: string
          description: Domain name with dash, e.g. 'dev-domainname-com'
          default: dev-domainname-com
          x-walrus-ui:
            group: Basic
            order: 6
        issuer_name:
          title: Issuer Name
          type: string
          description: Origin issuer name
          default: origin-ca-issuer
          x-walrus-ui:
            group: Basic
            order: 7
        issuer_kind:
          title: Issuer Kind
          type: string
          description: Origin issuer kind
          default: ClusterOriginIssuer
          x-walrus-ui:
            group: Basic
            order: 8
        pwd_metric_log:
          title: Pwd Metric Log
          type: string
          description: Password to define admin url access metrics and logs into Victoria
          default: _changeme_
          x-walrus-ui:
            group: Basic
            order: 9
      x-walrus-ui:
        groupOrder:
        - Basic
