openapi: 3.0.3
info:
  title: OpenAPI schema for template .
components:
  schemas:
    variables:
      type: object
      properties:
        helm_release_name:
          title: Helm Release Name
          type: string
          description: The name of the Helm release.
          default: victoria-metrics-auth
          x-walrus-ui:
            group: Basic
            order: 1
        namespace_name:
          title: Namespace Name
          type: string
          description: The namespace where the Helm release will be installed.
          default: victoria-system
          x-walrus-ui:
            group: Basic
            order: 2
        helm_chart_version:
          title: Helm Chart Version
          type: string
          description: The version of the victoria-metrics-auth Helm chart.
          default: 0.8.0
          x-walrus-ui:
            group: Basic
            order: 3
        resources:
          title: Resources
          type: object
          description: Resource limits and requests for the Helm release.
          default:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          additionalProperties:
            additionalProperties:
              type: string
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 4
        hpa_config:
          title: Hpa Config
          type: object
          description: Configuration for the HPA targeting for Victoria Auth Deployment
          default:
            max_replicas: 3
            min_replicas: 1
            target_cpu_utilization: 80
            target_memory_utilization: 80
          required:
          - max_replicas
          - min_replicas
          - target_cpu_utilization
          - target_memory_utilization
          properties:
            max_replicas:
              title: Max Replicas
              type: number
              x-walrus-ui:
                order: 2
            min_replicas:
              title: Min Replicas
              type: number
              x-walrus-ui:
                order: 1
            target_cpu_utilization:
              title: Target Cpu Utilization
              type: number
              x-walrus-ui:
                order: 3
            target_memory_utilization:
              title: Target Memory Utilization
              type: number
              x-walrus-ui:
                order: 4
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 5
        ingress_enabled:
          title: Ingress Enabled
          type: boolean
          description: Victoria Auth Ingress Enabled
          default: "true"
          x-walrus-ui:
            group: Basic
            order: 6
        domain_name:
          title: Domain Name
          type: string
          description: Domain name for Victoria Auth, e.g. 'dev.domainname.com'
          default: dev.domainname.com
          x-walrus-ui:
            group: Basic
            order: 7
        issuer_name:
          title: Issuer Name
          type: string
          description: Origin issuer name
          default: origin-ca-issuer
          x-walrus-ui:
            group: Basic
            order: 8
        issuer_kind:
          title: Issuer Kind
          type: string
          description: Origin issuer kind
          default: ClusterOriginIssuer
          x-walrus-ui:
            group: Basic
            order: 9
        ingress_class_name:
          title: Ingress Class Name
          type: string
          description: Ingress Class Name
          default: nginx
          x-walrus-ui:
            group: Basic
            order: 10
        pwd_metric_log:
          title: Pwd Metric Log
          type: string
          description: Password to define admin url access metrics and logs into Victoria
          default: change_me
          format: password
          writeOnly: true
          x-walrus-ui:
            group: Basic
            order: 11
      x-walrus-ui:
        groupOrder:
        - Basic
